#!/bin/bash -e
mypath="`realpath "$0"`"
myname="`basename "$mypath"`"
mydir="`dirname "$mypath"`"

die(){
    echo "$@" 1>&2
    exit 1
}

help() {
    cat <<EOF
Usage: ./makedoc [OPTIONS] -o output ROOT_src_dir ROOT_jl_dir

output        path of ROOTdoc.jl file to generate.
ROOT_src_dir  path of ROOT source the documentation must be read from.
ROOT_jl_dir   path of the ROOT.jl directort that must contain the Wrapit report under
              misc/jlROOT-report.txt 

OPTIONS:

--help  display this help.
--force force deletion of jldoc.sqlite file if it already exists.

EOF
}

if [ "$1" = --help ]; then
    help
fi

unset forced
if [ "$1" = --force ]; then
    forced=y
    shift
fi

[ $# = 4 -o "$1" != -o ] || { help; exit 1; }

output="$2"
rootsrc="$3"
rootjl="$4"

[ -d "$rootsrc" ] || die "ROOT_src_dir argument must be a directory."
[ -d "$rootjl" ] || die "ROOT_jl_dir argument must be a directory."
[ -f "$rootjl"/misc/jlROOT-report.txt ] || die "ROOT_jl_dir needs to contain misc/jlROOT-report.txt."

ontheway=()
if [ -e doxydoc ]; then
    if [ "$forced" = y ]; then
        rm -r doxydoc
    else
        ontheway+=(doxydoc)
    fi
fi
    
if [ -e "jldoc.sqlite" ]; then
    if [ "$forced" = y ]; then
        rm "jldoc.sqlite"
    else
        ontheway+=(jldoc.sqlite)
    fi
fi

if [ -n "${ontheway[*]}" ]; then
    die "File or directory on the way. ${ontheway[*]} must be moved or --force option must be used to foce their deletion."
fi
      

echo "Generate XML doc from ROOT source code..."
"$mydir"/makexmldoc "$rootsrc"
echo "Import information about wrapped types and methods into the database..."
"$mydir"/fillwrapped -o jldoc.sqlite "$rootjl"/misc/jlROOT-report.txt
echo "Import the generated documentation in the database jldoc.sqlite..."
"$mydir"/filldoxy -o jldoc.sqlite doxydoc/xml/
echo "Generate the $output file..."
"$mydir"/genjldoc -o "$output" jldoc.sqlite
