#!/usr/bin/env julia

import Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

import ROOTdocGen
using ROOTdocGen.ROOTdocDB

if length(ARGS) != 1
    println(stderr, "Usage: wrapped database")
    exit(1)
end

conn = ROOTdocGen.ROOTdocDB.Conn(ARGS[1])
println(join(wrapped_methods(conn), "\n"))